version: '3'

services:
  database:
    image: mysql
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'root'
    networks:
      - dev

    container_name: employee-manager-mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - 7070:80
    environment:
      PMA_HOST: database
    networks:
      - dev

    container_name: employee-manager-phpmyadmin

networks:
  dev:

volumes:
  database-data: