package com.example.employeemanager.Controllers;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.employeemanager.repository.UserRepository;
import com.example.employeemanager.models.User;
import com.example.employeemanager.models.User.Privilege;


@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (
        @RequestParam (name = "lastName") String lastName, 
        @RequestParam (name = "firstName") String fisrtName,  
        @RequestParam (name = "mail") String mail, 
        @RequestParam (name = "password") String password,
        @RequestParam (name = "privilege") Privilege privilege,
        @RequestParam (name = "hireDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) Date hireDate) {

        User n = new User();
        n.setFirstName(fisrtName);
        n.setLastName(lastName);
        n.setHireDate(hireDate);
        n.setPassword(password);
        n.setMail(mail);
        n.setPrivilege(privilege);
        userRepository.save(n);
        return "/home";
    }

    @PostMapping(path = "/update")
    public @ResponseBody String updateUser(@RequestParam int id, @RequestParam String firstName, @RequestParam String lastName, @RequestParam String password, @RequestParam Date hireDate, @RequestParam String mail, @RequestParam Privilege privilege) {
        User existingUser = userRepository.findById(id).orElse(null);
        if (existingUser != null) {
            existingUser.setFirstName(firstName);
            existingUser.setLastName(lastName);
            existingUser.setHireDate(hireDate);
            existingUser.setPassword(password);
            existingUser.setMail(mail);
            existingUser.setPrivilege(privilege);
            userRepository.save(existingUser);
            return "User updated";
        } else {
            return "User not found";
        }
    }

    @PostMapping(path = "/delete")
    public @ResponseBody String deleteUser(@RequestParam Integer id) {
        User userToDelete = userRepository.findById(id).orElse(null);
        if (userToDelete != null) {
            userRepository.delete(userToDelete);
            return "User deleted";
        } else {
            return "User not found";
        }
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}